local regions = {
    { id = 0, en = "Kingdom of San d'Oria", ja = "サンドリア王国" },
    { id = 1, en = "Republic of Bastok", ja = "バストゥーク共和国" },
    { id = 2, en = "Federation of Windurst", ja = "ウィンダス連邦" },
    { id = 3, en = "Grand Duchy of Jeuno", ja = "ジュノ大公国" },
    { id = 4, en = "Ronfaure", ja = "ロンフォール" },
    { id = 5, en = "Zulkheim", ja = "ザルクヘイム" },
    { id = 6, en = "Norvallen", ja = "ノルバレン" },
    { id = 7, en = "Gustaberg", ja = "グスタベルグ" },
    { id = 8, en = "Derfland", ja = "デルフラント" },
    { id = 9, en = "Sarutabaruta", ja = "サルタバルタ" },
    { id = 10, en = "Kolshushu", ja = "コルシュシュ" },
    { id = 11, en = "Aragoneu", ja = "アラゴーニュ" },
    { id = 12, en = "Fauregandi", ja = "フォルガンディ" },
    { id = 13, en = "Valdeaunia", ja = "バルドニア" },
    { id = 14, en = "Qufim", ja = "クフィム" },
    { id = 15, en = "Li'Telor", ja = "リ・テロア" },
    { id = 16, en = "Kuzotz", ja = "クゾッツ" },
    { id = 17, en = "Vollbow", ja = "ヴォルボー" },
    { id = 18, en = "Elshimo Lowlands", ja = "低地エルシモ" },
    { id = 19, en = "Elshimo Uplands", ja = "高地エルシモ" },
    { id = 20, en = "Tu'Lia", ja = "トゥー・リア" },
    { id = 21, en = "Dynamis", ja = "デュナミス" },
    { id = 22, en = "Movalpolos", ja = "ムバルポロス" },
    { id = 23, en = "Tavnazian Marquisate", ja = "タブナジア侯国" },
    { id = 24, en = "Tavnazian Archipelago", ja = "タブナジア群島" },
    { id = 25, en = "Promyvion", ja = "プロミヴォン" },
    { id = 26, en = "Lumoria", ja = "ルモリア" },
    { id = 27, en = "Limbus", ja = "リンバス" },
    { id = 28, en = "Western Aradjiah", ja = "西洋エラジア" },
    { id = 29, en = "West Aht Urhgan", ja = "西アトルガン地方" },
    { id = 30, en = "Mamool Ja Savagelands", ja = "マムージャ蕃国" },
    { id = 31, en = "Halvung Territory", ja = "ハルブーン傭兵団領" },
    { id = 32, en = "Arrapago Islands", ja = "アラパゴ諸島" },
    { id = 33, en = "Ruins of Alzadaal", ja = "アルザダール文明遺跡群" },
    { id = 34, en = "Ronfaure Front", ja = "ロンフォール戦線" },
    { id = 35, en = "Norvallen Front", ja = "ノルバレン戦線" },
    { id = 36, en = "Gustaberg Front", ja = "グスタベルグ戦線" },
    { id = 37, en = "Derfland Front", ja = "デルフラント戦線" },
    { id = 38, en = "Sarutabaruta Front", ja = "サルタバルタ戦線" },
    { id = 39, en = "Aragoneu Front", ja = "アラゴーニュ戦線" },
    { id = 40, en = "Fauregandi Front", ja = "フォルガンディ戦線" },
    { id = 41, en = "Valdeaunia Front", ja = "バルドニア戦線" },
    { id = 42, en = "Orcish Hosts", ja = "オーク帝国軍" },
    { id = 43, en = "Quadav Shieldwarriors", ja = "クゥダフ兵団" },
    { id = 44, en = "Yagudo Theomilitary", ja = "ヤグード教団軍" },
    { id = 45, en = "Dark Kindred", ja = "闇の王親衛隊" },
    { id = 46, en = "Abyssea", ja = "アビセア" },
    { id = 47, en = "The Threshold", ja = "スレッショルド" },
    { id = 48, en = "Abdhaljs", ja = "アブダルス" },
    { id = 49, en = "Sacred City of Adoulin", ja = "神聖アドゥリン都市同盟" },
    { id = 50, en = "Adoulin Isles", ja = "アドゥリン諸島" },
    { id = 51, en = "East Ulbuka Territory", ja = "東ウルブカ地方" },
    { id = 52, en = "Ra'Kaznar", ja = "ラ・カザナル" },
    { id = 53, en = "Escha", ja = "エスカ" },
    { id = 54, en = "The Far East", ja = "ひんがし" },
    { id = 97, en = "Gugru Blue", ja = "ググリュー洋を" },
    { id = 98, en = "Bastore Sea", ja = "バストア海" },       
    { id = 99, en = "Quon", ja = "クォン" },
    { id = 100, en = "Mindartia", ja = "ミンダルシア" },
    { id = 101, en = "Elshimo", ja = "エルシモ" },
}

return regions
